mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    initialization-mode: always
    schema: "schema.sql"
    url: ""
    username: "system"
    password: "oracle"
    hikari:
      auto-commit: true